apiVersion: v1
kind: Service
metadata:
  name: microk8s-app-service
spec:
  type: ClusterIP
  ports:
    - nodePort: 30000
      port: 10000
      targetPort: 10000
      protocol: TCP
  selector:
    app: microk8s-app